version: "3.4"
services:
  database:
    container_name: blog
    image: mariadb
    volumes:
      - ./docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ./docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=blog
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=blog
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    restart: always