server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  max-http-header-size: 80000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: 12345

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    show_sql: false
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
